<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Home.aspx.cs" Inherits="SpiderData.Home" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <link rel="stylesheet" href="grid.css" type="text/css" />
    <link rel="stylesheet" href="Button.css" type="text/css" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title></title>
        <style type="text/css">
        div{
        }
        .center-in-center{
            position: absolute;
            top: 15%;
            left: 18%;
        }
    </style>
</head>
<body>
    <form id="form1" runat="server">

        <asp:GridView ID="GridView1" runat="server" AllowPaging="True" AllowSorting="True" DataSourceID="LinqDataSource1"
            CssClass="mGrid"    
                    PagerStyle-CssClass="pgr"    
                    AlternatingRowStyle-CssClass="alt" GridLines="None" OnRowCommand="GridView1_RowCommand" Width="100%">
                    <AlternatingRowStyle CssClass="alt" />
                    <PagerStyle CssClass="pgr" />
            <Columns>
                        <asp:ButtonField CommandName="info" HeaderText="编辑查看" Text="编辑" />
                    </Columns>
        </asp:GridView>
        <asp:Button ID="Button1" runat="server" CssClass="buttonStyle" style="z-index: 1; left: 1050px; top: 73px; position: absolute" Text="返回" Visible="False" OnClick="Button1_Click" />
        <div class="center-in-center">
        <asp:DetailsView ID="DetailsView1" runat="server" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" BackColor="LightGoldenrodYellow" BorderColor="Tan" BorderWidth="1px" CellPadding="2" DataSourceID="LinqDataSource1" ForeColor="Black" GridLines="None" Height="500px" Visible="False" Width="100px" style="z-index: 1; left: -70px; top: 82px; position: absolute; height: 700px; width: 1200px" OnItemDeleted="DetailsView1_ItemDeleted" >
            <AlternatingRowStyle BackColor="PaleGoldenrod" />
            <EditRowStyle BackColor="DarkSlateBlue" ForeColor="GhostWhite" />
            <FooterStyle BackColor="Tan" />
            <HeaderStyle BackColor="Tan" Font-Bold="True" />
            <PagerStyle BackColor="PaleGoldenrod" ForeColor="DarkSlateBlue" HorizontalAlign="Center" />
        </asp:DetailsView>
            </div>
        <asp:LinqDataSource ID="LinqDataSource1" runat="server" ContextTypeName="SpiderData.DataClasses1DataContext" EnableInsert="True" EnableUpdate="True">
        </asp:LinqDataSource>
        <asp:Label ID="Label1" runat="server" Text="产品名称：" Font-Size="Large" style="z-index: 1; left: 347px; top: 18px; position: absolute; right: 538px"></asp:Label>
        <asp:TextBox ID="TextBox1" runat="server" style="z-index: 1; top: 16px; position: absolute; width: 325px; height: 24px; left: 459px; margin-top: 0px"></asp:TextBox>
        <asp:Label ID="Label2" runat="server" Text="生产厂商：" Font-Size="Large" style="z-index: 1; left: 348px; top: 62px; position: absolute"></asp:Label>
        <asp:TextBox ID="TextBox2" runat="server" style="z-index: 1; left: 457px; top: 65px; position: absolute; width: 329px; height: 19px"></asp:TextBox>
        <asp:Label ID="Label3" runat="server" Font-Size="Large" style="z-index: 1; left: 341px; top: 103px; position: absolute" Text="产品注册号："></asp:Label>
        <asp:TextBox ID="TextBox3" runat="server" style="z-index: 1; left: 457px; top: 108px; position: absolute; width: 328px; height: 23px"></asp:TextBox>
        <asp:Button ID="Button2" runat="server" Text="搜索"  OnClick="Button2_Click" BackColor="#66FF99" BorderColor="#99FFCC" Font-Size="Large" Height="35px" style="z-index: 1; left: 817px; top: 99px; position: absolute; width: 73px"/>
        <p>
            &nbsp;</p>
        <asp:LinkButton ID="LinkButton1" runat="server" OnClick="LinkButton1_Click" style="z-index: 1; left: 877px; top: 22px; position: absolute">注销登录</asp:LinkButton>
    </form>
</body>
</html>
